### PR TITLE
[20,21,38] Added new features

### LINKED ISSUE #20: BE: User Login
Provide User LogIn functionality. For manual test purposes use default test users from flyway script (#19 task). Also add Exceptions and Exception Handler.

### LINKED ISSUE #21: BE: User Registartion
Provide Registration functionality. Do not forget about exception handling mechanisms.

### LINKED ISSUE #38: BE: OAuth2 (via Google)
- Validate TokenId from Google
- If user does not exist register him as User-Manager
- Create Endpoint with user data response

### PR DESCRIPTION
**Pull request by vburmus**

### CODE REVIEW

**Review by maryushp — CHANGES_REQUESTED** [review]
Authentication response should also have user information (email, name, surname and role)

File: backend/src/main/java/org/fleetassistant/backend/auth/AuthenticationController.java [hunk 1]
```diff
@@ -0,0 +1,30 @@
...
+        AuthenticationResponse registerResponse = new AuthenticationResponse(authenticationService.register(request));
+        return ResponseEntity.ok(registerResponse);
+    }
+
+    @PostMapping("/authenticate")
+    public ResponseEntity<AuthenticationResponse> authenticate(@RequestBody AuthenticationRequest request) {
+        AuthenticationResponse authenticationResponse = new AuthenticationResponse(authenticationService.authenticate(request));
+        return ResponseEntity.ok(authenticationResponse);
+    }
+}
```
Comment (maryushp) [inline backend/src/main/java/org/fleetassistant/backend/auth/AuthenticationController.java:28]: provide controller method to get user data in response body (with no request body)

File: backend/src/main/java/org/fleetassistant/backend/auth/models/AuthenticationResponse.java [hunk 2]
```diff
@@ -0,0 +1,15 @@
...
+import lombok.NoArgsConstructor;
+import org.fleetassistant.backend.jwt.TokenDTO;
+
+@Data
+@Builder
+@AllArgsConstructor
+@NoArgsConstructor
+public class AuthenticationResponse {
+    private TokenDTO token;
+}
```
Comment (maryushp) [inline backend/src/main/java/org/fleetassistant/backend/auth/models/AuthenticationResponse.java:17]: Add to auth response also user data

**Review by maryushp — APPROVED** [review]
