### PR TITLE
LBF: Token Exception Resolver and Vehicles from user 

### LINKED ISSUE #87: BE: Vehicle assignment to User
Now vehicles in backend are not assigned to user (check create and readAll methods).
You should create vehicle and assign it to user making the request.
ReadAll method should return assigned vehicles to the user making the request.

### LINKED ISSUE #88: BE: Token Expiration error message

### PR DESCRIPTION
**Pull request by vburmus**

### CODE REVIEW

File: backend/src/main/java/org/fleetassistant/backend/vehicle/VehicleService.java [hunk 1]
```diff
@@ -36,7 +42,10 @@ public org.fleetassistant.backend.dto.Vehicle create(org.fleetassistant.backend.
     }
 
     public Page<org.fleetassistant.backend.dto.Vehicle> readAll(Pageable pageable) {
-        return vehicleRepository.findAll(pageable).map(entityToDtoMapper::vehicleToVehicleDto);
+        SecurityContext securityContextHolder = SecurityContextHolder.getContext();
```
Comment (maryushp) [inline backend/src/main/java/org/fleetassistant/backend/vehicle/VehicleService.java]: I would rather extract method "getLoggedOnUserId" into separate service (this method will be used throughout all the application). Also consider extracting method "getLoggedOnUserRole()" to the above service.

File: backend/src/main/java/org/fleetassistant/backend/vehicle/VehicleService.java [hunk 2]
```diff
@@ -36,7 +42,10 @@ public org.fleetassistant.backend.dto.Vehicle create(org.fleetassistant.backend.
...
+        Credentials credentials = (Credentials) securityContextHolder.getAuthentication().getPrincipal();
+        Long id = userService.getUserIdByEmail(credentials.getEmail());
+        return vehicleRepository.findAllByManagerId(id, pageable).map(entityToDtoMapper::vehicleToVehicleDto);
```
Comment (maryushp) [inline backend/src/main/java/org/fleetassistant/backend/vehicle/VehicleService.java]: Please, check if the logged on user is a manager or a driver and call appropriate repo method to get vehicles for specified user role. Alternatively do not forget to change this method (or expose a new one) during driver implementation task.

**Review by maryushp — CHANGES_REQUESTED** [review]

**Comment by maryushp** [comment]
Please, also change create vehicle method implementation. It should also consider user id (Loged on manager id)

**Review by maryushp — APPROVED** [review]
